### PR TITLE
REF add a base TF pickling class

### LINKED ISSUE #5: generalization to support new architectures
As pointed out by @beckermr, we could probably make a few changes here and there to make this code more useful for implementing a wider range of architectures.

I think we probably want to avoid increasing the scope too much, but some of the functionality for getting TF to work with sklearn isn't specific to classification/regression or MLPs (e.g., pickling, handling dense/sparse input matrices, partial_fit support), and I think a little work on this (e.g., adding some mixins or refactoring the base class) could be worthwhile.

Related to #4.

### PR DESCRIPTION
**Pull request by beckermr**
This PR adds a base pickling class for TensorFlow scikit-learn style estimators. It abstracts out all of the core functionality that could conceivably (right now) be shared by say a MLP and an autoencoder, for example.

Closes #5

### CODE REVIEW

**Comment by beckermr** [comment]
BTW, I passed on including a lot more the MLP base classes. It didn't seem like there was a lot of extra overhead in the other bits and the abstraction would come at the cost of clarity, which doesn't (yet) seem worth it.

**Comment by mheilman** [comment]
I just had some minor comments about the docs.  The functionality looks good.

**Comment by beckermr** [comment]
@mheilman I have fixed up the doc strings. This is ready for a second look!

**Comment by mheilman** [comment]
```
    __    ______________  ___
   / /   / ____/_  __/  |/  /
  / /   / / __  / / / /|_/ / 
 / /___/ /_/ / / / / /  / /  
/_____/\____/ /_/ /_/  /_/                                
```
(LGTM)

**Pull request merged**
