### PR TITLE
update changelog and bump version to 0.2.0

### PR DESCRIPTION
**Pull request by mheilman**
Preparing for making a release.

### CODE REVIEW

**Comment by mheilman** [comment]
@beckermr, version 0.2.0 sound OK since we've fixed some things and added the autoencoder?  This look OK?

**Comment by beckermr** [comment]
LGTM!

**Comment by beckermr** [comment]
Ack. Maybe we should update the conda env before tagging v0.2.0?

**Comment by mheilman** [comment]
@beckermr, OK now?

**Comment by mheilman** [comment]
oops. one moment...

**Comment by mheilman** [comment]
@beckermr, OK now?

**Comment by beckermr** [comment]
LGTM!

**Pull request merged**
