### PR TITLE
add a few badges to the README

### PR DESCRIPTION
**Pull request by mheilman**
This adds a few basic badges to the GitHub README.

### CODE REVIEW

**Comment by mheilman** [comment]
screen shot 2018-02-16 at 4 19 35 pm

**Comment by mheilman** [comment]
@jacksonllee, I think you're our resident badge expert :-)

**Comment by jacksonllee** [comment]
@mheilman Great badges!

I see from your screenshot that the license badge is on a second line -- is it intentional, or is it some unintended reStructuredText/GitHub parsing wackiness?

**Comment by mheilman** [comment]
I took a look at [how the good folks from scikit-learn did their badge formatting](https://raw.githubusercontent.com/scikit-learn/scikit-learn/master/README.rst), and now they show up on once line.

screen shot 2018-02-16 at 4 35 43 pm

**Pull request merged**
