### PR TITLE
fix initialization of random state in MLP partial_fit

### LINKED ISSUE #15: partial fit resets random state
`partial_fit` resets the random state for shuffling minibatches [https://github.com/civisanalytics/muffnn/blob/master/muffnn/mlp/base.py#L84]

There should probably be a private random state attribute on the class that gets set only when fitting or partial fitting the first time.

Thanks to @beckermr for catching this.

### PR DESCRIPTION
**Pull request by mheilman**
closes #15

### CODE REVIEW

**Comment by mheilman** [comment]
@beckermr, could you please take a look when you get a chance?

**Comment by beckermr** [comment]
I think you need to tuck `self._random_state` into the object state if the estimator has already been fit.

**Comment by beckermr** [comment]
You should add some sort of test to make sure that if you pickle and then unpickle estimator, the RNg just continues properly from where it was if the object is not refit. Maybe the new test you have, but where you do the same process on two estimators, but pickling one in the middle?

**Comment by mheilman** [comment]
Thanks for catching that.  OK now?

**Comment by beckermr** [comment]
LGTM!

**Pull request merged**
